### ISSUE TITLE
Invalid path in ingress

### ISSUE THREAD

**Issue by znat** [cowboysysop/charts#13]
```
mongo-express:
  basicAuthUsername: hello
  basicAuthPassword: hello
  mongodbAdminUsername: root
  mongodbAdminPassword: password
  ingress:
    enabled: true
    hosts:
      - name: http://my.domain.com
         paths:
          - path: /
```

Hi, thanks for this chart :)

I'm trying to setup the ingress. However, it gives me an `Invalid value: "map[path:/]": must be an absolute path`
Wondering if you could help figuring out what I'm missing. Thanks

**Comment by sebastien-prudhomme** [comment]
You should try with that:

```
  ingress:
    enabled: true
    hosts:
      - name: http://my.domain.com
         paths:
           - /
```

I'm using the default ingress implementation that is suggested when creating a chart with ```helm create```.
