### ISSUE TITLE
VPA: Unable to install on EKS fargate node (toleration issue)

### ISSUE THREAD

**Issue by comjf** [cowboysysop/charts#145]
Please add the ability for custom tolerations on the job that installs the CDRs (as you already do for the 3 vpa controllers)

https://github.com/cowboysysop/charts/blob/master/charts/vertical-pod-autoscaler/templates/crds/job.yaml

Without this, fargate only clusters are unable to operate: 
```
4m53s       Warning   FailedScheduling       pod/vertical-pod-autoscaler-crds-9sp7w                               0/13 nodes are available: 13 node(s) had taint {eks.amazonaws.com/compute-type: fargate}, that the pod didn't tolerate.
```

**Comment by sebastien-prudhomme** [comment]
Hi @comjf, I don't know AWS Fargate, all nodes are tainted with ```eks.amazonaws.com/compute-type=fargate:NoSchedule```?

**Comment by comjf** [comment]
👋 @sebastien-prudhomme -- Correct. If you're running a fargate only workload on EKS, then every node is tainted with that.

I thought I could use a `helm` postRenderer to hack that annotation into the job that loads the CRD... however even that is failing me (I think because the hook is fighting the patch?)

Here is my `fluxcd/flux2`  installation method: 
```
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vertical-pod-autoscaler
  namespace: kube-system
spec:
  interval: 1h
  chart:
    spec:
      chart: vertical-pod-autoscaler
      version: 4.0.4
      sourceRef:
        kind: HelmRepository
        name: cowboysysop
        namespace: flux-system
  ### We need this postRenderer to inject the EKS toleration on the `job` that installs the CRD
  ### Once https://github.com/cowboysysop/charts/issues/145 is addressed, this should be moved to values
  postRenderers:
    - kustomize:
        patchesStrategicMerge:
          - kind: Job
            apiVersion: batch/v1
            metadata:
              name: vertical-pod-autoscaler-crds
            spec:
              template:
                spec:
                  tolerations:
                    - effect: NoSchedule
                      key: eks.amazonaws.com/compute-type
                      value: fargate
  values:
    admissionController:
      tolerations:
        - effect: NoSchedule
          key: eks.amazonaws.com/compute-type
          value: fargate
    recommender:
      tolerations:
        - effect: NoSchedule
          key: eks.amazonaws.com/compute-type
          value: fargate
    updater:
      tolerations:
        - effect: NoSchedule
          key: eks.amazonaws.com/compute-type
          value: fargate
```

**Comment by sebastien-prudhomme** [comment]
@comjf Can you check this branch directly with Flux: https://github.com/sebastien-prudhomme/cowboysysop-charts/tree/crd-job-options/charts/vertical-pod-autoscaler

**Comment by comjf** [comment]
I didn't see a helm chart package for that branched code so I just threw it on my test repo and gave it a shot.

It works! I haven't verified all functionality of the service, however before it was dying on the early step of installing the CRDs and now that works!! 🎉 

```
pod/vertical-pod-autoscaler-admission-controller-7bf8cbb89f-2j6k6   1/1     Running   0          3m36s
pod/vertical-pod-autoscaler-recommender-766d976f48-6rtjg            1/1     Running   0          3m36s
pod/vertical-pod-autoscaler-updater-556b68ff85-62bbs                1/1     Running   0          3m36s 
```

here is my flux manifest for installing: 
```
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vertical-pod-autoscaler
  namespace: kube-system
spec:
  interval: 1h
  chart:
    spec:
      chart: vertical-pod-autoscaler
      version: 4.1.0
      sourceRef:
        kind: HelmRepository
        name: comjf-io
        namespace: flux-system
  values:
    crds:
      tolerations:
        - effect: NoSchedule
          key: eks.amazonaws.com/compute-type
          value: fargate
    admissionController:
      tolerations:
        - effect: NoSchedule
          key: eks.amazonaws.com/compute-type
          value: fargate
    recommender:
      tolerations:
        - effect: NoSchedule
          key: eks.amazonaws.com/compute-type
          value: fargate
    updater:
      tolerations:
        - effect: NoSchedule
          key: eks.amazonaws.com/compute-type
          value: fargate
```
