### ISSUE TITLE
Lighthouse Invalid project slug "example"

### ISSUE THREAD

**Issue by isatfg** [cowboysysop/charts#149]
Hi 

I have deployed the cowboysysop/lighthouse-ci helm chart and added the a site 
```
  sites:
    - urls:
        - https://www.mysite.com
      schedule: 00 14 * * *
      projectSlug: "example"
```

When the schedule runs I get this message

_PSI collection failure for Site #0: Invalid project slug "example"_

Also when I login to the UI I get a message saying 
_Run lhci wizard to setup your first project._
