### ISSUE TITLE
Making image registry configurable in vertical-pod-autoscaler

### ISSUE THREAD

**Issue by QuantumEnigmaa** [cowboysysop/charts#388]
Currently in vertical-pod-autoscaler, each component's deployment (admission-controller, recommender and updater) image is set to `"{{ .Values.admissionController.image.repository }}:{{ .Values.admissionController.image.tag }}"` in the templates (for the admission-controller here as example). 

However, in some cases, one may need to change the registry name without changing the repository itself. This would be especially useful in cases where one has the same repository in multiple registries (GCR, Harbor...) and has to use a specific registry for a chart deployed in a specific environment. 

I would thus suggest to split the image section as follows : 
```
image:
    registry: ""
    repository: ""
    tag: ""
    pullPolicy: ""
```
And update the `image:` field of each component's deployment template : `"{{ .Values.admissionController.image.registry }}/{{ .Values.admissionController.image.repository }}:{{ .Values.admissionController.image.tag }}"`

Keeping the admission-controller example, it would lead to this section in the `values` : 
```
image:
    registry: k8s.gcr.io
    repository: autoscaling/vpa-admission-controller
    tag: 0.13.0
    pullPolicy: IfNotPresent
```

I can create a PR for this if needed.
