### ISSUE TITLE
Documentation for ingress.hosts quotes a wrong field name

### ISSUE THREAD

**Issue by edemen** [cowboysysop/charts#39]
Hi
Reference for `ingress.hosts[0].name` should instead be to `ingress.hosts[0].host`

E.g., the actual working values would be:
```
ingress:
  enabled: true
  hosts:
    - host: me.example.com
      paths: 
       - /
```

Note `ingress.hosts.host` rather than `ingress.hosts.name`.
