### ISSUE TITLE
Add support for customizing containerPort in whoami chart

### ISSUE THREAD

**Issue by itmg1977** [cowboysysop/charts#441]
Hi, i am using `whoami` chart on an OpenShift cluster, where `ssc` cannot be added to a service account by a normal user. Therefore i cannot use containerPort `80`.

It would be convenient if i can use unprivileged port like `8080` by setting it with `values.yaml`:
```yaml
extraArgs:
  port: 2021
containerPort: 8080
```
