### ISSUE TITLE
Updater Does Not Get Namespace Configured Correctly

### ISSUE THREAD

**Issue by oliverisaac** [cowboysysop/charts#45]
https://github.com/cowboysysop/charts/blob/6504fb1128e7678fa738ee9ca83dc7369aff5fcb/charts/vertical-pod-autoscaler/templates/updater/deployment.yaml#L32

The VPA's updater component [uses the NAMESPACE env var](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/updater/main.go#L64) which is not set in the deployment. 

Would  you please add:

```
env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
```

Or, a way to set custom env:

```
{{- with .Values.env }}
env:
{{- toYaml . | nident 12}}
{{- end }}
```
