### ISSUE TITLE
Support for custom labels on ClusterRole resources

### ISSUE THREAD

**Issue by odise** [cowboysysop/charts#561]
I would like to add some dedicated labels on the `ClusterRole` resources deployed with the `vertical-pod-autoscaler` chart. 

Here is an example:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
  name: vertical-pod-autoscaler-vertical-pod-autoscaler-recommender
rules:
  ...
```

If you want me to provide a PR, don't hesitate to give me a wink. Thanks a bunch.
