### ISSUE TITLE
[charts/vertical-pod-autoscaler] Feature Request: Definitions of the PodDisruptionBudget in the Helm Chart

### ISSUE THREAD

**Issue by SatoruItaya** [cowboysysop/charts#59]
I think the PodDisruptionBudget is necessary to evict pods(admissionController, recommender and updater) safely.
So, I would like to define the PodDisruptionBudget in the Helm Chart and add a parameter which controls if Helm Chart creates PodDisruptionBudget or not.

**Comment by sebastien-prudhomme** [comment]
Hi @SatoruItaya , you're right, it will improve availability when replicaCount > 1

Such default configuration for one component would be fine for you?

```yaml
pdb:
  create: false
  minAvailable: 1
  # maxUnavailable: 1
```
