### ISSUE TITLE
Flowise: Add ability to connect to PostgreSQL using SSL

### ISSUE THREAD

**Issue by mattishaden** [cowboysysop/charts#593]
Feature request: Support for connecting to PostgreSQL using SSL. It was added in Flowise 1.4.8: https://github.com/FlowiseAI/Flowise/releases/tag/flowise%401.4.8

Example in: #592

**Comment by sebastien-prudhomme** [comment]
Hi, the feature is not that simple. Certificate authority needs also to be managed for people using a private CA, and internal PostreSQL chart must also have the option. I will first update the application version.

**Comment by IgorMilavec** [comment]
I've just created #674 that adds support for mounting extra volumes. With both #592 and #674 adding support for SSL is simple:
- Set externalPostgresql.ssl to true
- Create a ConfigMap with CA bundle and mount it
- Point the env variable NODE_EXTRA_CA_CERTS to the CA bundle

**Comment by IgorMilavec** [comment]
@mattishaden could you please rebase and update #592?

**Comment by jbmolle** [comment]
Since https://github.com/FlowiseAI/Flowise/releases/tag/flowise%401.4.12
there is the environment variable DATABASE_SSL_KEY_BASE64 for Flowise.

so we don't need to create a ConfigMap anymore, we just add the Postgres server certificate with DATABASE_SSL_KEY_BASE64 and it works

**Comment by mrkhachaturov** [comment]
> Since https://github.com/FlowiseAI/Flowise/releases/tag/flowise%401.4.12 there is the environment variable DATABASE_SSL_KEY_BASE64 for Flowise.
> 
> so we don't need to create a ConfigMap anymore, we just add the Postgres server certificate with DATABASE_SSL_KEY_BASE64 and it works

Can you please share  you values config? 
I cannot make it working with this configuration. 
```yaml
    extraEnvVars:
      - name: DATABASE_SSL
        value: "true"
      - name: DATABASE_SSL_KEY_BASE64
        valueFrom:
          secretKeyRef:
            name: flowdb-credentials-secret
            key: ca.crt
    extraEnvVarsSecret: flowdb-credentials-secret
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 3Gi
      storageClass: ceph-block
    config:
      username: "flowise"
    existingSecret: "flowise-credentials-secret"
    existingSecretKeyPassword: FLOWISE_PASSWORD
    externalPostgresql:
      ## @param externalPostgresql.enabled Whether to use an external PostgreSQL
      enabled: true
      host: 10.1.125.55
      port: 5000
      username: flowisedb_user
      existingSecret: "flowdb-credentials-secret"
      existingSecretKeyPassword: FLOWISE_DBUSER_PASSWORD
      database: flowisedbprod

```

**Comment by mrkhachaturov** [comment]
Make it working disabling externalPostgresql in values and defining values in env. 
```yaml
    extraEnvVars:
      - name: DATABASE_SSL
        value: "true"
      - name: DATABASE_TYPE
        value: "postgres"
      - name: DATABASE_HOST
        value: "10.1.125.55"
      - name: DATABASE_PORT
        value: "5000"
      - name: DATABASE_NAME
        value: "flowisedbprod"
      - name: DATABASE_USER
        value: "flowisedb_user"
      - name: DATABASE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: flowdb-credentials-secret
            key: FLOWISE_DBUSER_PASSWORD
      - name: DATABASE_SSL_KEY_BASE64
        valueFrom:
          secretKeyRef:
            name: flowdb-credentials-secret
            key: PG_CRT
    extraEnvVarsSecret: flowdb-credentials-secret
```
