### ISSUE TITLE
feat: add ability to specify liveness and readiness path

### ISSUE THREAD

**Issue by mconner** [cowboysysop/charts#62]
PR #35 added liveness and readiness probe configuration.  However, It does not work properly if you also configure ingress with a path. 
To get ingress to work with a path, I found that I had to provide a values.yaml override file with:

```
siteBaseUrl: /mongoexpress/

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /mongoexpress/$2
  hosts:
    - host: minikube.mshome.net
      paths:
        - /mongoexpress(/|$)(.*)

```
This works.  
However, because this changes the siteBasePath, the hardcoded path in templates/deployment.yaml is incorrect:
```
          livenessProbe:
            httpGet:
              path: /

```
(similarly, with readinesProbe. )
Path should instead be configurable:
`              path: {{ .Values.livenessProbe.path }}
`
