### ISSUE TITLE
Flowiseai: corrections/ additions to helm chart

### ISSUE THREAD

**Issue by danielstankw** [cowboysysop/charts#722]
Hi,
1. In case a service of type `LoadBalancer` is chosen, in the template the NodePort is required, why is that? - would it be possible to remove this dependency? 
2. Would you be able to add host aliases to the helm chart? 
`deployment.yaml`

```yaml
    spec:
      hostAliases:
        {{- toYaml .Values.hostAliases | nindent 8 }}
```

and then `values.yaml`
```yaml
extraDeploy: []

## @section Parameters

## @param replicaCount Number of replicas (do not change it)
replicaCount: 1

hostAliases:
- ip: "XXXX"
  hostnames:
  - "XXXXX"
```
